// Generated by https://quicktype.io

export interface Data {
    looks: Look[];
    lots:  any[];
}

export interface Look {
    id:             number;
    name:           string;
    price:          number;
    colors:         string[];
    categoryGroups: CategoryGroup[];
}

export interface CategoryGroup {
    categories: Category[];
    name?:      string;
}

export interface Category {
    name:    string;
    options: Option[];
    price?:  number;
    colors?: string[];
}

export interface Option {
    name: string;
}
